name: Run Django Tests

on: 
  pull_request:

jobs:
  run-django-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: nycmesh-dev
          POSTGRES_USER: nycmesh
          POSTGRES_PASSWORD: abcd1234
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      pelias:
        image: pelias/parser:latest
        ports:
          - 6800:3000
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: "Upgrade pip"
        run: "pip install --upgrade pip"
      - name: "Install package"
        run: pip install ".[dev]"
      - name: "Setup .env"
        run: |
          echo "\n" >> .env
          echo "DB_NAME='nycmesh-dev'" >> .env
          echo "DB_USER='nycmesh'" >> .env
          echo "DB_PASSWORD='abcd1234'" >> .env
          echo "DB_HOST='localhost'" >> .env
          echo "DB_PORT='5432'" >> .env
          echo "DJANGO_SECRET_KEY='k7j&!u07c%%97s!^a_6%mh_wbzo*$hl4lj_6c2ee6dk)y9!k88'" >> .env
          echo "PELIAS_ADDRESS_PARSER_URL='http://localhost:6800/parser/parse'" >> .env
          echo "QUERY_PSK='localdev'" >> .env
          echo "NN_ASSIGN_PSK='localdev'" >> .env
          echo "PANO_REPO_OWNER='nycmeshnet'" >> .env
          echo "PANO_REPO='node-db'" >> .env
          echo "PANO_BRANCH='master'" >> .env
          echo "PANO_DIR='data/panoramas'" >> .env
          echo "PANO_HOST='https://node-db.netlify.app/panoramas/'" >> .env
          echo "PANO_GITHUB_TOKEN='${{ secrets.PANO_GITHUB_TOKEN }}'" >> .env
      - name: Run Django Tests
        run: python3 src/manage.py test meshapi meshapi_hooks
